# Generated by Django 5.1.2 on 2024-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('oppurtunity', models.TextField(blank=True)),
                ('threat', models.TextField(blank=True)),
                ('strengthweakeness', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SrengthWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=225)),
                ('at_strength', models.TextField(blank=True)),
                ('at_weakness', models.TextField(blank=True)),
                ('profile', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.IntegerField(null=True)),
                ('alt_phone', models.IntegerField(null=True)),
                ('pdf_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
