# Generated by Django 5.1.2 on 2024-11-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0002_careerfields_srengthweakness_studentdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfields',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
