# Generated by Django 5.1.2 on 2024-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0003_careerfields_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerfields',
            old_name='example',
            new_name='example1',
        ),
        migrations.AddField(
            model_name='careerfields',
            name='example2',
            field=models.TextField(blank=True),
        ),
    ]
