# Generated by Django 5.1.2 on 2024-11-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0004_rename_example_careerfields_example1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=225)),
                ('at_strength', models.TextField(blank=True)),
                ('at_weakness', models.TextField(blank=True)),
                ('profile', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SrengthWeakness',
        ),
    ]
