# Generated by Django 5.1.2 on 2024-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0006_rename_oppurtunity_careerfields_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerfields',
            name='strengthweakeness',
        ),
        migrations.AddField(
            model_name='careerfields',
            name='strength_weakeness',
            field=models.TextField(blank=True),
        ),
    ]
