# Generated by Django 5.1.2 on 2024-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0007_remove_careerfields_strengthweakeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerfields',
            name='strength_weakeness',
        ),
        migrations.AddField(
            model_name='careerfields',
            name='strength_weakness',
            field=models.TextField(blank=True),
        ),
    ]
