# Generated by Django 5.1.2 on 2024-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0008_remove_careerfields_strength_weakeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfields',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='example1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='example2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
