# Generated by Django 5.1.2 on 2024-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0009_alter_careerfields_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfields',
            name='strength_weakness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
