# Generated by Django 5.1.2 on 2024-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0010_alter_careerfields_strength_weakness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfields',
            name='description',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='example1',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='example2',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='opportunity',
            field=models.TextField(blank=True, default='NULL'),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='strength_weakness',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
        migrations.AlterField(
            model_name='careerfields',
            name='threat',
            field=models.TextField(blank=True, default='NULL'),
        ),
    ]
