# Generated by Django 5.1.2 on 2024-11-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0011_alter_careerfields_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
