# Generated by Django 5.1.2 on 2024-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_test', '0013_alter_studentdetail_alt_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='grade',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='school_name',
            field=models.TextField(default='exampleschool', max_length=225),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
